# Generated by Django 5.2.17 on 2026-08-26 09:57

import tracker.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', tracker.models.UserManager()),
            ],
        ),
    ]