# Generated by Django 5.2.17 on 2026-08-27 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0008_remove_tag_color'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name': 'Progetto', 'verbose_name_plural': 'Progetti'},
        ),
        migrations.AlterModelOptions(
            name='timeentry',
            options={'verbose_name': 'Attività', 'verbose_name_plural': 'Attività'},
        ),
        migrations.RenameField(
            model_name='project',
            old_name='name',
            new_name='nome',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='owner',
            new_name='responsabile',
        ),
        migrations.RenameField(
            model_name='tag',
            old_name='created',
            new_name='creato',
        ),
        migrations.RenameField(
            model_name='tag',
            old_name='name',
            new_name='nome',
        ),
        migrations.RenameField(
            model_name='tag',
            old_name='hours',
            new_name='ore',
        ),
        migrations.RenameField(
            model_name='timeentry',
            old_name='description',
            new_name='descrizione',
        ),
        migrations.RenameField(
            model_name='timeentry',
            old_name='end',
            new_name='fine',
        ),
        migrations.RenameField(
            model_name='timeentry',
            old_name='start',
            new_name='inizio',
        ),
        migrations.RenameField(
            model_name='timeentry',
            old_name='project',
            new_name='progetto',
        ),
        migrations.RenameField(
            model_name='timeentry',
            old_name='jira_issue_type',
            new_name='tipo_ticket',
        ),
        migrations.RenameField(
            model_name='timeentry',
            old_name='user',
            new_name='utente',
        ),
        migrations.AlterUniqueTogether(
            name='tag',
            unique_together={('nome',)},
        ),
    ]
