# Generated by Django 5.2.17 on 2026-08-26 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_tag_project_tags_timeentry_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeentry',
            name='description',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
