# Generated by Django 5.2.17 on 2026-08-26 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_timeentry_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeentry',
            name='jira_issue_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
