# Generated by Django 5.2.17 on 2026-08-26 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0006_tag_color'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tag',
            unique_together={('name',)},
        ),
        migrations.AddField(
            model_name='tag',
            name='hours',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.RemoveField(
            model_name='tag',
            name='owner',
        ),
    ]
