# Generated by Django 5.2.17 on 2026-08-27 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0007_alter_tag_unique_together_tag_hours_remove_tag_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='color',
        ),
    ]
